# Sed commmand https://www.geeksforgeeks.org/sed-command-in-linux-unix-with-examples/

: <<'COMMENT'

 sed command stads for stream editor and it can perform  lots of
 functions like searching, find and replace

 Syntax

 sed OPTIONS... [SCRIPT] [INPUTFILE...] 

COMMENT


$cat > geekfile.txt

: <<'COMMENT'
 Replacing or substituting string : 
 Sed command is mostly used to replace the text in a file. 
 The below simple sed command replaces the word “unix” with “linux” in the file.

COMMENT

$sed 's/unix/linux/' geekfile.txt

# Here the “s” specifies the substitution operation. The “/” are delimiters. The “unix” is the search pattern and the “linux” is the replacement string. By default, the sed command replaces the first occurrence of the pattern in each line and it won’t replace the second, third…occurrence in the line.



# 2 Replacing the nth occurrence of a pattern in a line : Use the /1, /2 etc flags to replace the first, second occurrence of a pattern in a line. The below command replaces the second occurrence of the word “unix” with “linux” in a line.

$sed 's/unix/linux/2' geekfile.txt

# 3 Replacing all the occurrence of the pattern in a line : The substitute flag /g (global replacement) specifies the sed command to replace all the occurrences of the string in the line.
$sed 's/unix/linux/g' geekfile.txt

# 4 Replacing from nth occurrence to all occurrences in a line : Use the combination of /1, /2 etc and /g to replace all the patterns from the nth occurrence of a pattern in a line. The following sed command replaces the third, fourth, fifth… “unix” word with “linux” word in a line.
$sed 's/unix/linux/3g' geekfile.txt

# 5 Parenthesize first character of each word : This sed example prints the first character of every word in parenthesis.
$ echo "Welcome To The Geek Stuff" | sed 's/\(\b[A-Z]\)/\(\1\)/g'

# 6. Replacing string on a specific line number : You can restrict the sed command to replace the string on a specific line number. An example is
$sed '3 s/unix/linux/' geekfile.txt

# 7. Duplicating the replaced line with /p flag : The /p print flag prints the replaced line twice on the terminal. If a line does not have the search pattern and is not replaced, then the /p prints that line only once.
$sed 's/unix/linux/p' geekfile.txt

# 8. Printing only the replaced lines : Use the -n option along with the /p print flag to display only the replaced lines. Here the -n option suppresses the duplicate rows generated by the /p flag and prints the replaced lines only one time.
$sed -n 's/unix/linux/p' geekfile.txt

# 9. Replacing string on a range of lines : You can specify a range of line numbers to the sed command for replacing a string.
# Here the sed command replaces the lines with range from 1 to 3.
$sed '1,3 s/unix/linux/' geekfile.txt

# 10. Deleting lines from a particular file : SED command can also be used for deleting lines from a particular file. SED command is used for performing deletion operation without even opening the file Examples: 1. To Delete a particular line say n in this example
Syntax:
$ sed 'nd' filename.txt
Example:
$ sed '5d' filename.txt

# 2. To Delete a last line
Syntax:
$ sed '$d' filename.txt

# 3. To Delete line from range x to y
Syntax:
$ sed 'x,yd' filename.txt
Example:
$ sed '3,6d' filename.txt

# 4. To Delete from nth to last line
Syntax:
$ sed 'nth,$d' filename.txt
Example:
$ sed '12,$d' filename.txt

# 5. To Delete pattern matching line
Syntax: 
$ sed '/pattern/d' filename.txt
Example:
$ sed '/abc/d' filename.txt


#  
#
